$:
  vscode:
    - services:
        - vscode
        - docker
      docker:
        image: docker.cnb.cool/mathdeng/cnb
        dockerUser: $CNB_TOKEN_USER_NAME
        dockerPassword: $CNB_TOKEN
      stages:
        - name: 安装依赖
          script:
            - npm install

  push:
    - imports:
        - https://cnb.cool/mathdeng/secret/-/blob/main/env.yml
      stages:
        - name: sync to github
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/mathdeng/next.git
            auth_type: https
            username: ${GITHUB_USERNAME}
            password: ${GITHUB_TOKEN}
